---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: {{ .Values.fleet.name | default "default-fleet" }}-autoscaler
  {{- if .Values.fleet.labels }}
  labels:
    {{- range $key, $val := .Values.fleet.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  fleetName: {{ .Values.fleet.name | default "default-fleet" }}
  policy:
    {{- if ( eq .Values.autoScaler.type "webhook" ) }}
    type: Webhook
    webhook:
      # use a service, or URL
      service:
        name: autoscaler-webhook-service
        namespace: default
        path: scale
      # optional for URL defined webhooks
      # url: ""
      # caBundle:  optional, used for HTTPS webhook type
    {{- else }}
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10
    {{- end }}

