---
# https://agones.dev/site/docs/reference/fleet/
# https://agones.dev/site/docs/reference/gameserver/

apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: {{ .Values.fleet.name }}
  labels:
    {{- range $key, $val := .Values.fleet.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  replicas: 2
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      metadata:
        labels:
          {{- range $key, $val := .Values.fleet.labels }}
          {{ $key }}: {{ $val | quote }}
          {{- end }}
      ports:
      - name: default
        containerPort: 7654
      health:
        initialDelaySeconds: 30
        periodSeconds: 15
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      template:
        spec:
          containers:
          - name: simple-game-server
            image: gcr.io/agones-images/simple-game-server:0.13
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"

