---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}
  namespace: argocd

  {{- if .Values.app.labels }}
  labels:
    {{- range $key, $val := .Values.app.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
    
spec:
  project: {{ .Values.project.name }}

  source:
    repoURL: https://couchpartygames.github.io/fleet
    targetRevision: {{ .Values.app.version }}
    chart: fleet
    helm:
      externalValueFiles:
        - repoURL: https://github.com/KaiReichart/argo-test-values.git
          targetRevision: main
          valueFiles:
            - values.yaml

  destination:
    name: {{ .Values.project.clusterName }}
    namespace: 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3 
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
