---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler-webhook-service
  labels:
    app: autoscaler-webhook
spec:
  selector:
    app: autoscaler-webhook
  ports:
  - port: 8000
    protocol: TCP
    name: https
    targetPort: autoscaler 

---
# Deploy a pod to run the autoscaler-webhook code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-webhook
  namespace: default
  labels:
    app: autoscaler-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler-webhook
  template:
    metadata:
      labels:
        app: autoscaler-webhook
    spec:
      #serviceAccount: autoscaler-webhook
      containers:
      - name: autoscaler-webhook
        image: gcr.io/agones-images/autoscaler-webhook:0.4
        imagePullPolicy: Always
        ports:
        - name: autoscaler
          containerPort: 8000
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
